### ISSUE TITLE
Question: Are you guys planning to put this on hackage?

### ISSUE THREAD

**Issue by frmsaul** [uber/queryparser#14]

**Comment by frmsaul** [comment]
If so when? 
If not, why?
Is there a way I could help make this happen?

PS: This is a really awesome project! Thanks for making it.

**Comment by h4v0kh3l1** [comment]
Yes, we can definitely put queryparser on hackage. Thanks for pinging us!

I can get it in by the end of the week, but let me see if I have time today to do that. I'll ping ya later today about that.

**Comment by frmsaul** [comment]
Wow, thanks for being so quick to responsive!
Defiantly let me know!

**Comment by h4v0kh3l1** [comment]
So, I didn't get all the way to hackage, but made some steps towards it. I'll get back to this later in the week.

**Comment by frmsaul** [comment]
Thanks

**Comment by h4v0kh3l1** [comment]
@frmsaul 

Alright, uploaded some packages!

http://hackage.haskell.org/package/queryparser
http://hackage.haskell.org/package/queryparser-vertica
http://hackage.haskell.org/package/queryparser-hive
http://hackage.haskell.org/package/queryparser-presto

There's still work to be done, there's no haddocs on these packages yet, and we don't have an automated build system set up yet. I'll make tracking tasks for those, but other than that let us know how it's working out for you.

Cheers!

**Comment by frmsaul** [comment]
Thanks!
