### ISSUE TITLE
use `traverse` instead of `overJust`

### ISSUE THREAD

**Issue by Fuuzetsu** [uber/queryparser#24]
You have
```
module Data.Maybe.More where

overJust :: Applicative f => (t -> f a) -> Maybe t -> f (Maybe a)
overJust _ Nothing = pure Nothing
overJust f (Just x) = Just <$> f x
```

but this is exactly [traverse for Maybe](https://hackage.haskell.org/package/base-4.10.0.0/docs/src/Data.Traversable.html#line-230).

**Comment by h4v0kh3l1** [comment]
So it is. Thanks @Fuuzetsu for pointing that out!

I doubt I'll have time this week to go through and clean it up, but this looks like a great issue for a first-time contributor.
