### ISSUE TITLE
Installation troubles

### ISSUE THREAD

**Issue by eyaltrabelsi** [uber/queryparser#34]
First of all the idea seems super cool!!!!
I am using macOS sierra, i have run the following:
- I have docker installed 
-  entered eval "$(docker-machine env default)" into bashrc and run source on it
- brew install ghc haskell-stack

When i tried to run the demo using:
-  stack ghci 
- followed by :set prompt "> " 
- import Demo will result  
     > no location info>: error:   Could not find module ‘Demo’  It is not a module in the current program, or in any known package.""

**Comment by h4v0kh3l1** [comment]
hmm, let me see if I can recreate it.

what does `stack test` look like for you?

**Comment by etrabelsi** [comment]
when i run stack test I get 
> Perhaps you need to run 'stack init'?

when i run stack init I get
> Looking for .cabal or package.yaml files to use to init the project. In order to init, you should have an existing .cabal file. Please try "stack new" instead. CallStack (from HasCallStack):  error, called at src/Stack/Solver.hs:542:9 in stack-1.6.5-69HPMPlUImE3riImkanr1P:Stack.Solver

**Comment by h4v0kh3l1** [comment]
Unfortunately, I'm not able to recreate what you're seeing. Go figure. 

From the readme, have you tried `stack setup`?

**Comment by dlthomas** [comment]
@etrabelsi What directory are you running `stack ghci`, etc from?  The behavior sounds like you're running it from somewhere without a `stack.yaml` file.
