### ISSUE TITLE
run this tool via command line

### ISSUE THREAD

**Issue by geniusayush** [uber/queryparser#39]
I am using this tool for a hackathon with **0 knowldege about haskell.**
So rather than going via interactive shell can we use something via command Line??
I am trying to run this library via bash script..
ex 
stack ghci Demo DemoAllAnalysis "select a,b,c from t1"
if anything  else can be used here it would be great .

Also it would be much helpful if i can use the tool to build multiple sql lines without hav ing to rebuild stack everytime

**Comment by dlthomas** [comment]
Haskell's a compiled language, and it'd be a pretty simple exercise to wrap the library in an executable, at which point using it from a script would be trivial.  What kind of analysis are you wanting to do?  I expect the hardest part would be building the catalog (assuming that's required).

**Comment by dlthomas** [comment]
(I have less bandwidth to help today than often - you might also want to try #haskell)

**Comment by lukas-mi** [comment]
I created a wrapper https://github.com/lukas-mi/vertica-query-analyser, which implements the majority of queryparser features, also it builds a catalog from provided DDL queries.

**Comment by clojurians-org** [comment]
i write a nix haskell script can be run as command line:
you can run just like this:
```
export NIX_PATH=~/.nix-defexpr/channels

ls metadata_sample/hive_*.sql | bin/lineage_hive_generator.hs

find . -name "*.sql" | grep hive | bin/lineage_hive_generator.hs
```

you can find the details:
https://github.com/clojurians-org/simple-datahub/blob/master/contrib/metadata-etl/bin/lineage_hive_generator.hs
