### ISSUE TITLE
could the python service wrapper open source as well?

### ISSUE THREAD

**Issue by feng-tao** [uber/queryparser#50]
The blog(https://eng.uber.com/queryparser/) mentioned: ```Queryparser is internally deployed as a Haskell artifact, running behind a Python service wrapper for interoperability with the rest of Uber’s infrastructure. ```. Would it be possible to open source that python service wrapper as well?

**Comment by dlthomas** [comment]
Of course I can't speak to what decision Uber might make here, but as the original author of the wrapper I don't know that it'd be all that valuable - the entire purpose of the wrapper was integration with Uber's particular internal ecosystem and it does very little beyond that.

**Comment by feng-tao** [comment]
@dlthomas yeah, I don't mean to ask uber to open source that exact wrapper. As a dev without any experience with haskell , I would like to see an example on how to use python to interact with this tool for query processing. E.g I would like to see if we could leverage to get table linage, table usage etc.

**Comment by h4v0kh3l1** [comment]
@feng-tao At its core, the wrapper provides a transport connector between our service and our production environment. Most of the work to implement this is in standing up a Haskell service that deserializes inputs into Queryparser objects, as well as maintain a catalog to provide for analytics. 

In particular here, Haskell's JSON support is key to getting this going. While we don't have a JSON serializer for our analytical objects, implementing that is straightforward. At this point, the work needed is to implement the catalog with your specific use case, and implement a JSON round-trip. Python was only for the connector, you can achieve interoperability by focusing instead on JSON.

**Comment by feng-tao** [comment]
thanks @dlthomas @h4v0kh3l1 for the input.
cc @jinhyukchang

**Comment by lukas-mi** [comment]
@feng-tao I created a wrapper https://github.com/lukas-mi/vertica-query-analyser, which implements queryparser analysis features,  also it builds a catalog from provided DDL queries.
